import { Button } from "@aceuidev/button";

export default function DefaultSection() {
  return (
    <section className="demo-section">
      <h2>Button · Default</h2>
      <div className="demo-row">
        <Button onPress={() => alert("Pressed!")}>Click me</Button>
        <Button onPress={() => alert("Pressed!")}>Another button</Button>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque unde odio delectus quidem enim, ex recusandae perferendis laudantium temporibus fugit. Similique numquam dolor delectus dignissimos optio. Saepe maiores similique necessitatibus.</p>
      </div>
    </section>
  );
}
